---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes

  tasks:
    - name: Create the samples app
      k8s:
        state: present
        definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
        wait: yes
      vars:
        cr_file: 'apps_v1alpha1_testoperator.yaml'

    - name: Add assertions here
      assert:
        that: false
        fail_msg: FIXME Add real assertions for your operator
