---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: Create test kind cluster
      command: kind create cluster --name osdk-test-2 --kubeconfig {{ kubeconfig }}
